### ISSUE TITLE
Odd black lines

### ISSUE THREAD

**Issue by TenoTrash** [jpatillo/IIC_without_ACK#1]
Hello! I'm using this library with a nodeMCU ESP8266, and have some black lines along the fonts, my display works (is a simple 128 x 64) but I don't have a clue on how to solve it. Can you help me?

**Comment by jpatillo** [comment]
If you have found an issue by now, I would like to hear about it. Unfortunately I am unable to help because all of my hardware is currently in storage and I can't run tests.

**Comment by TenoTrash** [comment]
Same problem here, don't worry!
Product works the very same!
Cheers from Argentina
